### ISSUE TITLE
Automate scraping PIAs

### ISSUE THREAD

**Issue by ondrae** [18F/privacy-tools#13]
**What:** 
Automate scraping PIAs. Start writing code to scrape PIAs and saving their data to our inventory.

**Why:**
We want to automate the gathering of data for any agency that may want to use our tool. When working with GSA, we just pulled all the data from the PIAs by hand.

**How:**
1. Create a new `pia_scraper.py`.
2. Be able to point it at an agencies list of PIAs
3. It should download all those PDFs
4. It should save the full text of each PDF, saving each as a text file, saved in our [PIA full text folder](https://drive.google.com/drive/folders/1xLcQBbTWrEkm7GYf7ERqs4CFpRimzDnr) on GDrive.
5. It should parse that full text file and start saving structured data, such as we have in[ our spreadsheet we made by hand](https://docs.google.com/spreadsheets/d/1uVEwPVMHtPjSL0aUUKNXmPEGx1RqpB0g_gZ87CQzVAc/edit#gid=0).
6. It should output that structured data for all PIAs in a single CSVs.

**Acceptance:**
Andrew approves that PIA data is being automatically scraped from the GSA website and saved in a structured way to a CSV.

**Comment by peterrowland** [comment]
These might be useful:
https://medium.com/@umerfarooq_26378/python-for-pdf-ef0fac2808b0
https://github.com/pdfminer/pdfminer.six

**Comment by ondrae** [comment]
Another project at 18F is using https://github.com/jcushman/pdfquery. It is built on top of pdfminer.

**Comment by ondrae** [comment]
I'm trying to figure out if it is worth the effort to have our PIA scraper pull the different sections we want, or just stop at getting the full text.

My first attempt at pulling the paragraphs describing PII (by grabbing any text between `3.2` and `3.3`) was able to get some result for 88% of the PIAs. Is that good enough?

**Comment by nikzei** [comment]
Next: need to decide whether there's value in writing code to pull text from other sections.

**Comment by nikzei** [comment]
Not for now.
