### ISSUE TITLE
Start saving full text of privacy documents

### ISSUE THREAD

**Issue by ondrae** [18F/privacy-tools#14]
**What:**
Save the full text of all of the PIAs and SORNs

**Why:**
We want to learn about what is possible by exposing the full text of PIAs and SORNs. We think we will need to reduce the info available to just the columns we think is important, but lets check that assumptions.

**How:** 
PIA full text should be taken care of in #13 . SORNs full text needs to done in this story.
1. Add code to start saving the full text of the SORNs as separate text file.
2. We’ll need to use the [XML full text links ](https://www.federalregister.gov/documents/full_text/xml/2015/06/04/2015-13701.xml)and get rid of the XML tags.

**Acceptance:**
Show Andrew that SORNs full text are being saved as text files in our [SORN full text folder](https://drive.google.com/drive/folders/1xnsGRZlgKUTsRcLFRZwSTGdR4STpbh4s) on Google Drive.

**Comment by nikzei** [comment]
Not for now.
