### ISSUE TITLE
Add “authority” to raw data prototype

### ISSUE THREAD

**Issue by ondrae** [18F/privacy-tools#15]
**What:** 
Marcela requested we add the “authority” to the data in our inventory. Let's learn about what she meant, why adding this would be valuable, and see whether it's worth adding to the prototype version we're finishing up in Sprint 2.

**Acceptance:**
- [x] Ask Marcela what and why. There is an “Authority for maintenance of the system:” section in SORNs. Is that what she wants? Is there something like it in PIAs?
- [ ] After clarifying, add code to our scraper to pull the sections she is requesting.
- [ ] Make sure the data ends up in this spreadsheet: [4. Data for prototype](https://docs.google.com/spreadsheets/d/1pZVqimeaSbwu9lutaItkLaXykPft_Ncj2ZA8I2g5FoM/edit#gid=0)
- [ ] Get that deployed. Download it as a CSV. Save it to [our prototype repository](https://github.com/ondrae/pii-at-gsa/tree/master/_data), with the name all-raw-data.csv, replacing the old data.
- [ ] decide how/whether to incorporate "authority" into our inventory dash. 
- [ ] Test whether it's useful. If we can we incorporate this addition before testing our latest prototype version (testing to begin week of 2/24), that would be GREAT

**Comment by nikzei** [comment]
### What are these authorities?
To be compliant with the Privacy Act, our SORNs should cite authorities that require certain types of PII to achieve a purpose and the PIAs that reference those SORNs should share that purpose either directly or indirectly. 

### Why authorities are useful to list:
- To enable privacy officers to make sure that the law listed as justifying the PII collection matches up with the collection's purpose. If it doesn't match up, they can find the error, correct it.

- To enable the public to hold GSA accountable; by knowing the relevant laws, individuals will be able to call out if GSA collects data outside of that law's parameters

- to build trust with the public

### Where authorities are listed:
PIA template section 1.1: What legal authority and/or agreements allow GSA to collect, maintain, use, or disseminate the information?

SORN template: AUTHORITY FOR MAINTENANCE OF THE SYSTEM: [The specific authority that authorizes the maintenance of the records in the system]. 

### Should we add them?
I believe so - their value seems particularly important in making these records meaningful. Particularly so if our work eventually becomes the foundation for a public-facing data source.

**Comment by nikzei** [comment]
Closing this card, making a new one for mocking what it might look like to be able to search by authority.

If this becomes a feature, we won't pick it up until our first slice is in production.
