### ISSUE TITLE
ATO Process

### ISSUE THREAD

**Issue by ondrae** [18F/privacy-tools#19]
Our project must go through the ATO process. An overview for 18F is summarized at https://before-you-ship.18f.gov/

We believe that we won't have to do the entirety of the ATO process, because we are going to be using static data on Federalist. Details at https://before-you-ship.18f.gov/infrastructure/federalist/

We will still go through all the beginning steps though, as they will help guide us to a clear and approved deployment in production.

This issue will document the work we do towards the ATO process.

**Comment by ondrae** [comment]
[Asked on Slack](https://gsa-tts.slack.com/archives/C039MHHF8/p1581552833201100) for what steps in the ATO process they think we should still do.

**Comment by ondrae** [comment]
The ATO checklist is at https://before-you-ship.18f.gov/ato/checklist/

Here are the parts we should do, even though we are not getting an ATO.
- [ ] Enable protected branches for the project repository.
- [ ] Turn on DAP? https://digital.gov/guides/dap/ - Instead of GAnalytics?
- [ ] If this is a new system, add a prominent Beta label to the site.

Separately Federalist has a launch checklist at https://federalist.18f.gov/documentation/launch-checklist/
- [ ] Contact the Federalist team; as part of our compliance process, GSA will complete a security scan of your site and let you know of the results within a week.
-  [ ] Set up custom url

**Comment by nikzei** [comment]
Let's keep the checks above for the future, if we end up creating a web app that needs an ATO.
