### ISSUE TITLE
Get a production gsa.gov url

### ISSUE THREAD

**Issue by ondrae** [18F/privacy-tools#29]
What:
Get a production gsa.gov url

How:
- [x] Ask in #infrastructure about the process
- [x] Talk with Richard and GSA OSC
- [ ] Get a live url

Federalist says that getting a subdomain is easier for setting up the SSL certs. It appears all the other tools that GSA hosts have subdomains too.

**Comment by peterrowland** [comment]
We make the request here https://gsa.service-now.com/

**Service Catalog > Enterprise Services > DNS**

I think we want to request **internal + external DNS**

I e-mailed Richard and Marcela to ask them what domain they wanted.

**Comment by ondrae** [comment]
We did not a get a GSA url during phase three. It is looking veery possible during phase four though.
