### ISSUE TITLE
SORN scraper improvements

### ISSUE THREAD

**Issue by ondrae** [18F/privacy-tools#3]
### What
Improve the SORN scraper by having it look for these alternative headlines to a few sections.

Just under half of GSAs SORNs use the following for the header of the Routine Use section
`ROUTINE USES OF THE RECORDS IN THE SYSTEM, INCLUDING TYPES OF USERS AND THE PURPOSES OF THE USES:`

A handful use `PURPOSE(S)` or `PURPOSES:` for that section.

### Why
To have our SORN scraper scrape more data. We filled in the missing data by hand for not.

### How
Have the [scraper method](https://github.com/18F/privacy-tools/blob/master/sorn_scraper.py#L66) accept multiple possible headings. I abstracted it into a single method. If it gets complicated, just have each of the `get_pii()` or `get_system_name()` methods do have their own logic around headers to look for.

**Comment by nikzei** [comment]
Not for now.
