### ISSUE TITLE
Add Authority to Dashboard

### ISSUE THREAD

**Issue by ondrae** [18F/privacy-tools#45]
- [x] Automate getting authority from PIAs and SORNs
- [ ] Analyze the authorities to learn more about them. Can we figure out the right links to include?
- [x] Add authority to dashboard like in Igor's mockups.
- [x] Figure out staging/deploying new data to spreadsheet.

**Comment by ondrae** [comment]
Here is how many Authorities we are able to scrape so far. https://github.com/18F/privacy-tools/blob/authority/gsa_pias.csv

**Comment by ondrae** [comment]
Here is a preview build with Authority included. https://cg-9341b8ea-025c-4fe2-aa6c-850edbebc499.app.cloud.gov/preview/18f/privacy-dashboard/authority/

Its got the full authority text scraped from SORNs. It has hand picked law refences for all the PIAs.

**Comment by ondrae** [comment]
@igorkorenfeld What do you think? Shippable? Do one round of questions about the authority with Marcela, then ship if she gives thumbs up?

**Comment by igorkorenfeld** [comment]
I think it's looking good, and yes I agree that sounds like a good plan. Show it to Marcela, let her work with it and ask her questions and then adjust from there. The only thing I am still noticing is that there are a couple of cases where em dashes and section signs are surrounded by weird characters. Some sort of encoding issue? If you look at the "Travel Charge Card Program." and "Travel System" you'll see what I mean.

**Comment by peterrowland** [comment]
Looks like it is an encoding problem with certain characters.

'§§§§ ' > 'Â§Â§Â§Â§â' 
U+00A7 : SECTION SIGN
U+2009 : THIN SPACE

'5701—' > '5701â' 
U+2014 : EM DASH
U+0094 : <control-0094> (CANCEL CHARACTER [CCH])

We can fix what we have with a quick find and replace in the spreadsheet. The source of the issue probably needs to be addressed in the scraper.

**Comment by igorkorenfeld** [comment]
Makes sense, I wonder why it handles some section signs ok but not others. But that sounds like a good solution.
