### ISSUE TITLE
[Sprint 4]  Create confidence inspiring instructions for Richard and Marcela on how to use the spreadsheet in relation to our PII Dashboard.

### ISSUE THREAD

**Issue by peterrowland** [18F/privacy-tools#46]
Consider if this is needed this sprint or later.

**Comment by peterrowland** [comment]
Draft:
https://docs.google.com/document/d/1JRoOykvm8Ur3G7VlPCS0fXmGh82oehtBSgRtM5kkw8o/edit

**Comment by ondrae** [comment]
https://github.com/18F/privacy-dashboard/blob/master/data-instructions.md
