### ISSUE TITLE
Bug: Some highlighting persists after clearing filter/search term

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/privacy-tools#48]
When doing a search for some term and then clearing out the search box, items containing the original search term are still highlighted on some pages. 

To replicate: 
1. Type "SSN" in the search box and hit enter
2. Delete "SSN" from the search box and hit enter
3. Go to page 4 of the results and scroll down. There should be 3 cards that still have a highlight

![image](https://user-images.githubusercontent.com/52677065/78036925-da891080-7338-11ea-859c-848c8108c709.png)

**Comment by ondrae** [comment]
Interesting, I'll dig in.

**Comment by ondrae** [comment]
It's also not highlighting results on other pages.
