### ISSUE TITLE
Check our assumption about OMB A130

### ISSUE THREAD

**Issue by ondrae** [18F/privacy-tools#6]
**What:**
Check our assumption that OMB A130 requires agencies to keep an inventory of PII, not just the list of categories of records in the PIAs and SORNs. I’m assuming we need come up with a clean list of PII at an agency. Do we? How is OMB A130 being enforced? Who is checking? What do they want to see for compliance?

**Why:** 
There is a good chance that our best way to gain adoption at other agencies is by making it easy for them to comply with OMB A130.

**How:**
Talk with Richard about that assumption. Talk with others he recommends.

**Acceptance:**
Share what you learn with the team.

**Comment by nikzei** [comment]
@nikzei to have new info for team on Thursday, 2/13.

**Comment by nikzei** [comment]
According to Marcela, a list of PII reported in PIAs is enough for the PII inventory. This means that the PII does not need to be clean.
